plugins {
    id 'com.android.application'
}

android {
    namespace 'com.videocollector.app'
    compileSdk 35

    defaultConfig {
        applicationId "com.videocollector.app"
        minSdk 23
        targetSdk 35
        versionCode 11
        versionName "7.0"
    }
}

dependencies {
    implementation files('libs/nativecore.aar')
}
